config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :app do
    resource :newsletter, only: %i[edit show update]
    resources :issues 
    namespace :issues do
      post 'send/:id', to: 'sending#create', as: 'send'
    end
  end

  resources :newsletters, only: %i[index show] do
    resources :issues, only: :show
    resources :subscribers, only: :create
    resources :links, only: :create
  end

  resources :links, only: :create

  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  extend FriendlyId

  belongs_to :newsletter

  validates :content, presence: true
  validates :title, presence: true, uniqueness: { scope: :newsletter_id }
  validates :send_at, current_time: true
  validates :slug, presence: true, format: {
    with: /\A[a-z\-0-9\_]+\z/, message: 'invalid format'
  }, uniqueness: { scope: :newsletter_id }

  friendly_id :slug, use: :slugged

  def perform
    set_number
    set_title
    set_slug
  end

  def set_number
    self[:number] =
      if newsletter.issues.count.positive?
        # We don't use .last here, because
        # current_user.newsletter.issues.build instance is last,
        # but we need last created in the database instance.
        newsletter.issues.order(created_at: :desc).limit(1).last.number + 1
      else
        1
      end
  end

  def set_title
    self[:title] = "#{newsletter.title} — Issue ##{number}"
  end

  def set_slug
    self[:slug] = "#{self[:title].parameterize}-#{SecureRandom.hex(3)}"
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :newsletter
  validates :url, presence: true

  def mark_repeat_domain!
    update(repeat_domain: true) if repeat_domain?
  end

  private

  def repeat_domain?
    domain = URI.parse(url).host
    Link.where('url like?', "%#{domain}%").any?
  end
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  extend FriendlyId

  belongs_to :user
  has_many :issues
  has_many :subscribers
  has_many :links

  validates :slug, presence: true, format: {
    with: /\A[a-z\-0-9\_]+\z/, message: 'invalid format'
  }, uniqueness: true

  friendly_id :slug, use: :slugged
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :newsletter

  validates :name, presence: true
  validates :email, email: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :newsletter
end

app/controllers/app/issues/sending_controller.rb
class App::Issues::SendingController < ApplicationController
  before_action :set_current_issue, only: :create
  
  def create
    if @issue[:sent_at]
      redirect_to app_newsletter_url, warning: "#{@issue[:title]} has already been sent."
    else
      IssueSendingJob.perform_later(@issue[:id])
      redirect_to app_newsletter_url, success: "#{@issue[:title]} was succesfully sended."
    end
  end

  private

  def set_current_issue
    @issue = current_user.newsletter.issues.friendly.find(params[:id])
  end
end
 

app/controllers/app/issues_controller.rb
module App
  class IssuesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_newsletter, only: %i[show edit update destroy]
    before_action :set_issue, only: %i[show edit update destroy]
    def show; end

    def new
      @issue = Issue.new
    end

    def edit; end

    def create
      @issue = current_user.newsletter.issues.build(issue_params)
      @issue.perform
      if @issue.save
        redirect_to [:app, @issue], success: 'Issue was successfully created.'
      else
        render :new
      end
    end

    def update
      if @issue.update(issue_params)
        redirect_to [:app, @issue], success: 'Issue was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @issue.destroy
      redirect_to app_newsletter_url, success: 'Issue was successfully destroyed.'
    end

    private

    def set_newsletter
      @newsletter = current_user.newsletter
    end

    def set_issue
      @issue = @newsletter.issues.friendly.find(params[:id])
    end
    
    def issue_params
      params.require(:issue).permit(:content, :send_at)
    end
  end
end

app/controllers/app/newsletters_controller.rb
module App
  class NewslettersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_newsletter, only: %i[edit update]

    def show
      @newsletter = Newsletter.includes(:issues).find_by(user: current_user)
      @issues     = @newsletter.issues.page(params[:page]).per(20).decorate
    end

    def edit; end

    def update
      if @newsletter.update(newsletter_params)
        redirect_to app_newsletter_path, success: 'Newsletter updated.'
      else
        render :edit
      end
    end

    private

    def set_newsletter
      @newsletter = current_user.newsletter
    end

    def newsletter_params
      params.require(:newsletter).permit(:title, :description, :welcome_text, :slug)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types(
    :primary, :secondary, :success, :danger, :warning, :info, :light, :dark
  )
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
    @issue = Issue.friendly.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def create
    @newsletter = Newsletter.friendly.find(params[:newsletter_id])
    @link       = @newsletter.links.build(link_params)
    check_if_suggested

    if @link.save
      redirect_to @newsletter,
        success: "You successfully offer link to \"#{@newsletter.title}\"."
    else
      errors = @link.errors.full_messages.join(', ')
      redirect_to @newsletter,
        danger: "Offering link failed! #{errors}."
    end
  end


  private

  def link_params
    params.require(:link).permit(:url, :title, :description)
  end

  def check_if_suggested
    if @newsletter.user == current_user
      @link.suggested = false
    else
      @link.suggested = true
    end
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  def index
    @newsletters = Newsletter.all
  end

  def show
    @newsletter = Newsletter.friendly.find(params[:id])
    @issues     = @newsletter.issues.page(params[:page]).per(20).decorate
    @subscriber = @newsletter.subscribers.build
    @link       = @newsletter.links.build
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create
    @newsletter = Newsletter.friendly.find(params[:newsletter_id])
    @subscriber = @newsletter.subscribers.build(subscriber_params)

    if @subscriber.save
      NewsletterMailer.new_subscriber(@subscriber).deliver_later

      redirect_to @newsletter,
        success: "You successfully subscribed to \"#{@newsletter.title}\"."
    else
      errors = @subscriber.errors.full_messages.join(', ')
      redirect_to @newsletter,
        danger: "Subscription failed! #{errors}."
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :email)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super

    Newsletter.create(
      user_id: resource.id, title: "#{resource.email}'s newsletter",
      slug: "newsletter-#{resource.id}"
    )
  end

  def update
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_side_menu?
    controller_name.eql?('issues') && action_name.eql?('show')
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-danger" id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/app/issues/_form.html.slim
= form_for [:app, @issue], html: {class: 'new-issue-form'} do |f|
  - if @issue.errors.any?
    = render 'layouts/object_errors', object: @issue

  .form-group
    = f.label :content, class: 'newsletters-form__label'
    = f.text_area :content, class: 'newsletters-form__input new-issue-form__textarea', rows: 6
    - unless @issue[:sent_at]
      = datetime_local_field(:issue, :send_at)
  .newsletters-form-btns.new-issue-form-btns
    => f.submit 'Save', class: 'newsletters-form__btn new-issue-item__btn'
    => link_to 'Save & Submit', '#', class: 'newsletters-form__btn new-issue-item__btn'

app/views/app/issues/edit.html.slim
.d-flex.flex-column.align-items-center.edit-issue
  .newsletters-form-wrap
    h1.text-center.default-title.edit-issue__title #{@issue.title}

    = render 'form'

app/views/app/issues/new.html.slim
.d-flex.flex-column.align-items-center.new-issue
  .newsletters-form-wrap
    h1.text-center.default-title.new-issue__title New issue

    = render 'form'

app/views/app/issues/show.html.slim
.issue
  h1.default-title.issue-title = @issue.title

  p.issue-content
    = @issue.content

  small.text-muted
    i
      - if @issue[:sent_at]
        = "Issue was sent on #{@issue[:sent_at]}"
      - elsif @issue[:send_at]
        = "Issue will depart on #{@issue[:send_at]}"

  - unless @issue[:sent_at]
    - if @issue[:send_at]
      = button_to 'Send issue',
        app_issues_send_path,
        data: { confirm: "You have planned to send your issue on #{@issue[:send_at]}. Do you want to send it now?" },
        class: 'issue-btn-wrap__btn issue__send-btn'

    - else
      = button_to 'Send issue',
        app_issues_send_path,
        data: { confirm: "Are you sure?" },
        class: 'issue-btn-wrap__btn issue__send-btn'

  .issue-btn-wrap
    => link_to 'Edit', edit_app_issue_path(@issue), class: 'issue-btn-wrap__btn'
    = link_to 'Destroy', [:app, @issue], data: { confirm: 'Are you sure?' },
    method: :delete, class: 'issue-btn-wrap__btn'

app/views/app/newsletters/edit.html.slim
.d-flex.flex-column.align-items-center.edit-newsletter
  h1.default-title.edit-newsletter__title Newsletter settings

  .newsletters-form-wrap
    = form_for [:app, @newsletter], html: {class: 'edit-newsletter-form'} do |f|

      .form-group.edit-newsletter-item
        p.newsletters-form__label Newsletter title
        p.text-muted How about your name, or the topic you’ll write about?
        = f.text_field :title, class: 'newsletters-form__input'

      .form-group.edit-newsletter-item
        p.newsletters-form__label Newsletter description
        p.text-muted Describe what your issues will be about
        = f.text_area :description, class: 'newsletters-form__input edit-newsletter-item__textarea', rows: 3

      .form-group.edit-newsletter-item
        p.newsletters-form__label Welcome text
        p.text-muted
          | Enter a welcome message that will be sent to new subscribers
        = f.text_area :welcome_text, class: 'newsletters-form__input edit-newsletter-item__textarea', rows: 3

      .form-group.edit-newsletter-item
        p.newsletters-form__label Newsletter slug
        p.text-muted Slug
        = f.text_field :slug, class: 'newsletters-form__input'

      .newsletters-form-btns
        = f.submit 'Save', class: 'newsletters-form__btn'

app/views/app/newsletters/show.html.slim
.d-flex.flex-column.align-items-center.view-newsletter
  h1.default-title = @newsletter.title
  p.view-newsletter__description = @newsletter.description

  - @issues.each do |issue|
    .card.issue-card
      .card-body
        span.issue-card__num
          = issue.display_number
        .issue-card-content
          .issue-card-content-top
            => link_to issue.title, newsletter_issue_path(@newsletter, issue), class: 'issue-card-content-top__name'
            span.issue-card-content-top__date
              = issue.created_at
          p.issue-card-content__description
            = truncate(issue.content, length: 70)

  = paginate @issues

app/views/app/newsletters/update.html.slim
h1 Newsletter#update
p Find me in app/views/newsletter/update.html.slim

app/views/issues/show.html.slim
.issue
  h1.default-title.issue-title = @issue.title

  p.issue-content
    = @issue.content

app/views/layouts/_flash_messages.html.slim
.alerts-list.container
  - flash.each do |flash_type, flash_content|
    .row.justify-content-end
      div{class="alert alert-#{flash_type} alert-dismissible fade show" role="alert"}
        = button_tag class: 'close', data: { dismiss: 'alert' }, aria: { label: 'Close' } do
          span aria-hidden="true"
            | &times;
        = flash_content

app/views/layouts/_navbar.html.slim
header.header
  .container
    .row
      .header-inner
        .logo
          = link_to 'Random Newsletter', root_path, class: 'header-inner__link logo__link'
        .user
          nav.navbar.navbar-expand-lg.navbar-expand.navbar-light.user-nav
              ul.navbar-nav.user-list
                li.nav-item.user-list__item
                  = link_to 'Newsletters', newsletters_path, class: 'header-inner__link user-list__link'
                - if user_signed_in?
                  li.nav-item.user-list__item
                    = link_to 'New issue', new_app_issue_path, class: 'header-inner__link user-list__link'
                  li.nav-item.dropdown.user-list__item
                    a#navbarDropdownMenuLink.dropdown-toggle.header-inner__link aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="http://example.com"
                      / = current_user.email
                      i.fa.fa-user-o aria-hidden="true"
                    .user-dropdown-mnu.dropdown-menu aria-labelledby="navbarDropdownMenuLink"
                      = link_to 'Newsletter settings', edit_app_newsletter_path,
                        class: 'dropdown-item header-inner__link user-dropdown-mnu__link'
                      = link_to 'View your newsletter', app_newsletter_path,
                        class: 'dropdown-item header-inner__link user-dropdown-mnu__link'
                      = link_to 'Your settings', edit_user_registration_path,
                        class: 'dropdown-item header-inner__link user-dropdown-mnu__link'
                      = link_to 'Logout', destroy_user_session_path, method: :delete,
                        class: 'dropdown-item header-inner__link user-dropdown-mnu__link'
                - else
                  li.nav-item.user-list__item
                    = link_to 'Sign In', new_user_session_path, class: 'header-inner__link user-list__signin-up user-list__link'
                    = link_to new_user_session_path
                      i.fa.fa-sign-in aria-hidden="true"

                  li.nav-item.user-list__item
                    = link_to 'Sign Up', new_user_registration_path, class: 'header-inner__link user-list__signin-up user-list__link'
                    = link_to new_user_registration_path
                      i.fa.fa-user-plus aria-hidden="true"

app/views/layouts/_object_errors.html.slim
.alert.alert-danger.object-errors
  ul
    - object.errors.full_messages.each do |message|
      li= message

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomNewsletter</title>
    <%= csrf_meta_tags %>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900|Open+Sans|Raleway:400,700,900" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <section class="newsletters">
      <div class="container">
        <%= render 'layouts/flash_messages' if flash.present? %>
        <div class="row">
          <% if render_side_menu? %>
            <div class="col-sm-9">
              <%= yield %>
            </div>
            <div class="col-sm-3">
              <!-- TODO -->
            </div>
          <% else %>
            <%= yield %>
          <% end %>
        </div>
      </div>
    </sectiion>
    <!-- Fontawesome icons -->
    <script src="https://use.fontawesome.com/ffe9ee26ec.js"></script>
  </body>
</html>

app/views/links/_form.html.slim
.d-flex.justify-content-center.links
  .newsletters-form-wrap
    = form_for [@newsletter, @link] do |f|
      - if @link.errors.any?
        = render 'layouts/object_errors', object: @link

      .form-group
        = f.label :url, class: 'newsletters-form__label'
        = f.text_field :url,   class: 'newsletters-form__input'
      .form-group
        = f.label :title, class: 'newsletters-form__label'
        = f.text_field :title,  class: 'newsletters-form__input'
      .form-group
        = f.label :description, class: 'newsletters-form__label'
        = f.text_field :description,  class: 'newsletters-form__input'
      .newsletters-form-btns
        = f.submit 'Offer link', class: 'newsletters-form__btn'

app/views/newsletters/index.html.slim
.newsletters-catalog
  h1.text-center.newsletters-catalog__title Everything you want to know, can search in katalog
  .newsletters-card-list
    - @newsletters.each do |n|
        .card.newsletters-card.newsletters-card-gradient
          .card-body.newsletters-card-overlay
            .newsletters-card-content__background
            .newsletters-card-content
              = link_to n.title, n, class: 'card-title newsletters-card-content__title'
              / p.card-text.newsletters-card-txt__description = "#{n.description}"
              .newsletters-card-author
                = image_tag 'http://fillmurray.com/500/500', class: 'newsletters-card-author__img'
                p.newsletters-card-author__name Phil Murray

app/views/newsletters/show.html.slim
.d-flex.flex-column.newsletter-page
  h1.text-center.default-title.newsletter-page__title = @newsletter.title
  p.text-center.newsletter-page__description = @newsletter.description

  = render 'subscribers/form'

  = render 'links/form'

  .newsletter-issues-list.d-flex.flex-column.align-items-center
    - @issues.each do |issue|
        .card.issue-card
          .card-body
            span.issue-card__num
              = issue.display_number
            .issue-card-content
              .issue-card-content-top
                => link_to issue.title, newsletter_issue_path(@newsletter, issue), class: 'issue-card-content-top__name'
                span.issue-card-content-top__date
                  = issue.created_at
              p.issue-card-content__description
                = truncate(issue.content, length: 70)
    hr
  = paginate @issues
br

app/views/static_pages/home.html.slim
.d-flex.justify-content-center.newsletters-main
  h1.default-title.font-weight-bold.newsletters-main__title Be smart with random neslewtter.

app/views/subscribers/_form.html.slim
.d-flex.justify-content-center.subscriber
  .newsletters-form-wrap
    = form_for [@newsletter, @subscriber] do |f|
      - if @subscriber.errors.any?
        = render 'layouts/object_errors', object: @subscriber

      .form-group
        = f.label :name, class: 'newsletters-form__label'
        = f.text_field :name,   class: 'newsletters-form__input'
      .form-group
        = f.label :email, class: 'newsletters-form__label'
        = f.text_field :email,  class: 'newsletters-form__input'
      .newsletters-form-btns
        = f.submit 'Subscribe', class: 'newsletters-form__btn'